# Hugging Face Transformers
    

In [1]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis", model="bert-base-uncased")
result = classifier("The actors were very convincing")
print(result)

/Users/leopoldotodisco/Desktop/hands-on/env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.


[{'label': 'LABEL_0', 'score': 0.6458877325057983}]


In [2]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

model_name = "huggingface/distilbert-base-uncased-finetuned-mnli"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = TFAutoModelForSequenceClassification.from_pretrained(model_name)

token_ids = tokenizer(["I like soccer. [SEP] We all love soccer!", "Joe Lived for a very long time. [SEP] Joe is old."], return_tensors="tf", padding=True)

token_ids

All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


{'input_ids': <tf.Tensor: shape=(2, 15), dtype=int32, numpy=
array([[ 101, 1045, 2066, 4715, 1012,  102, 2057, 2035, 2293, 4715,  999,
         102,    0,    0,    0],
       [ 101, 3533, 2973, 2005, 1037, 2200, 2146, 2051, 1012,  102, 3533,
        2003, 2214, 1012,  102]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 15), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [3]:
output = model(token_ids)

output

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-2.1123812 ,  1.1786768 ,  1.4101024 ],
       [-0.01478113,  1.0962449 , -0.9919958 ]], dtype=float32)>, hidden_states=None, attentions=None)

In [4]:
import tensorflow as tf

y_probas = tf.keras.activations.softmax(output.logits)

y_probas

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.01619703, 0.43523493, 0.5485681 ],
       [0.22656052, 0.68817157, 0.08526786]], dtype=float32)>

In [5]:
y_pred = tf.argmax(y_probas, axis=1)

y_pred # 0 = contraddizione, 2 = neutrale, 1 = implicazione, il risultato è l'array numpy  
# qui la prima sequenza è neutrale, ma la seconda sequenza è un'implicazione.

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 1])>